### ISSUE TITLE
Switch to using GitHub auth

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#1]
Info here: http://haacked.com/archive/2014/04/24/octokit-oauth/

**Comment by kevinchalet** [comment]
FYI, we have an ASP.NET 5 authentication middleware for GitHub on aspnet-contrib that should make this thing much easier to implement: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers

``` csharp
app.UseGitHubAuthentication(options => {
    options.ClientId = "client_id";
    options.ClientSecret = "client_secret";
    options.SaveTokensAsClaims = true;
});
```

``` csharp
// Extract the access token from a MVC controller.
var token = Context.User.FindFirst("access_token")?.Value;
```

**Comment by Eilon** [comment]
@PinpointTownes thanks for the tips!!

**Comment by kevinchalet** [comment]
FYI, we're now on NuGet.org and we have an alpha1 release for ASP.NET 5 beta7: https://www.nuget.org/packages/AspNet.Security.OAuth.GitHub/ :tada:

**Comment by Eilon** [comment]
@PinpointTownes just updated, thanks again! https://github.com/Eilon/ProjectKIssueList/commit/d322145e54031ac356939fee1cff04e6d6e5b4c7
