### ISSUE TITLE
Group PRs and issues better

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#10]
It's a bit tricky, but it would be nice to show PRs within the existing groupings on the site.

It's tricky because with PRs it's usually most interesting _who_ opened it, and they aren't assigned to anyone (for team PRs). Also, they don't generally have milestones.

**Comment by muratg** [comment]
Following up on today's quick discussion, we could totally consider tracking (at least external) PRs in a milestone and assign them to people.

**Comment by Eilon** [comment]
@muratg I made some change that _I_ at least like in how stuff is displayed. Now it shows all the working issues, opened PRs, and other issues per person. Then at the bottom it shows only the PRs that aren't from one of the people in the group. I also improved the "Group by milestone" and "Group by repo" tabs to show the combined issue/PR view.

**Comment by muratg** [comment]
Looks great! I think it'll be much more easier to be able to track open PRs this way.
