### ISSUE TITLE
Review all auth related stuff to make sure it's good

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#112]
1. General review of Hubbup auth
2. Some issues with redirecting after login where GitHub reports some mismatch: https://github.com/Eilon/Hubbup/issues/21
3. And also not sure the best way to handle GitHub OAuth scope changes. There are apparently some GitHub APIs that can help with this, but need to figure out the right way to plumb them through.

**Comment by Eilon** [comment]
@tratcher

**Comment by Tratcher** [comment]
Note: In the github portal why does the auth callback url not include "/signin-github"?

**Comment by Eilon** [comment]
Closing for now then.
