### ISSUE TITLE
Sometimes issue mover app doesn't do anything

### ISSUE THREAD

**Issue by mairaw** [Eilon/Hubbup#122]
**Describe the bug**
After adding Move from and to fields info, app does nothing.

**To Reproduce**
1. Go to https://hubbup.io/Mover
2. Paste the URL to the issue on the Move from field
3. Paste the URL to the target repo on the To field
4. Nothing happens

**Expected behavior**
It would load the information for me to move the bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/12971179/72188677-bfe57200-33af-11ea-858d-bbea27a6dac6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Chromium
 - Version 80.0.361.23

**Comment by Eilon** [comment]
Hmm interesting, I haven't seen this in quite some time. If you see this again, can you click the `Show debug info` button at the bottom and send me the snippets? The content **MIGHT** contain sensitive info (I'm not sure), so please **email it to me**.

![image](https://user-images.githubusercontent.com/202643/72195568-caac0100-33c7-11ea-8ef0-c59ae513e2b0.png)

**Comment by mairaw** [comment]
It was just empty whenever that happened. Note that I managed to move with the tool eventually after opening a different browser or browser window.

**Comment by Eilon** [comment]
Weird, I just had it happen to me too, but seemingly random. I'll see if I can add some debug logic to it to help understand what's happening.

**Comment by mairaw** [comment]
Yep, it's just random.

**Comment by Eilon** [comment]
OK I *think* this is now fixed! I hit this error myself, thought I fixed it, saw it again, then made an actual fix: https://github.com/Eilon/Hubbup/commit/6ae5292ce07988beee07109730d1369cda1e41d8

I do think this is legit fixed now, so I'm closing this issue. If you see it again please let me know!
