### ISSUE TITLE
Show all items assigned to each person regardless of labels/milestone

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#16]
But still show only open bugs.

**Comment by muratg** [comment]
And ignore "Backlog" of course :)

**Comment by Eilon** [comment]
Maybe... but shouldn't backlog items be unassigned?

**Comment by muratg** [comment]
Sure, I just went ahead and cleared Backlog items which were assigned.

**Comment by Eilon** [comment]
Nice :smile:

**Comment by Eilon** [comment]
@muratg I think [this comment](https://github.com/Eilon/ProjectKIssueList/issues/18#issuecomment-140584157) was intended to go here:

> If we keep a list of ICs per lead, we can additional features:
> - Highlight everyone that's not reporting to me but have tasks in my query 
> - Highlight my ICs tasks that are not in my query

**Comment by Eilon** [comment]
The site now shows everyone's items that are _within_ the repo set.

It also needs to start showing a person's items across the entire org. Need to figure out a good way to do this. Could issue a query per person within the main org (could have a main org for each repo set) and exclude items that are already in the existing `allIssues` set.

**Comment by Eilon** [comment]
The site can now do this, though the list of repos need to be explicitly included.

E.g. I removed the `kcoreext` repo set and merged it into the `kcore` repo set, but for `kcoreext` it shows only issues assigned to people in the person set (plus PRs _created_ by those people).
