### ISSUE TITLE
Have link for super triage query for each repo set

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#18]
Generate queries like Magnanimous Murat's triage query.

**Comment by muratg** [comment]
If we keep a list of ICs per lead, we can additional features:
- Highlight everyone that's not reporting to me but have tasks in my query 
- Highlight my ICs tasks that are not in my query

**Comment by Eilon** [comment]
@muratg the feature you mention here is part of this issue: https://github.com/Eilon/ProjectKIssueList/issues/16

**Comment by Eilon** [comment]
This issue is just about generating super queries on GitHub.com - not about rendering anything else on the site.
