### ISSUE TITLE
Change OAuth redirect to go to the originally requested URL

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#21]
It now always redirects to `/`.

Previously there was often a GitHub OAuth redirect error stating the destination URL was bad.

Info here:
- General info: https://developer.github.com/v3/oauth/#redirect-urls
- Specific error: https://developer.github.com/v3/oauth/#redirect-uri-mismatch

**Comment by Eilon** [comment]
More info about the error:

* https://developer.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/

**Comment by Tratcher** [comment]
No repro once I got my Authorization callback URL set up correctly. Note it does not seem to verify the path (/signin-github). Getting everything unified to https helped.
