### ISSUE TITLE
Externalize the list of repo sets and repos

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#23]
Need to stop hard-coding it. Currently have to re-deploy the app to change the repo sets.

**Comment by muratg** [comment]
I was thinking of 3 different ways of approaching this:
1. Traditional solution: Keep it in a SQL DB and use EF
2. Easiest solution: Read the file (possibly in CSV format) from a gist :)
3. Fancy solution: I can actually implement a microservice :)

**Comment by Eilon** [comment]
I'll have an `IRepoSetProvider` and I'll implement the `StaticRepoSetProvider`. When you implement a microservice, I'll write a provider for that :wink:

**Comment by Eilon** [comment]
This is now partially done. There's a separate JSON file but it's still part of the app. It does refresh the JSON file every 5 minutes. Next up is retrieving the file over HTTP.

**Comment by Eilon** [comment]
This is totally done. Just need to send PRs to https://github.com/Eilon/Hubbup-data and the site refreshes every N minutes (N = 5 at this time).
