### ISSUE TITLE
Triage super queries have only last milestone excluded

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#29]
GitHub web site queries seem to consider only the last excluded milestone in a milestone query. For example, in the query `-milestone:M1 -milestone:M2` only the `M2` milestone will be excluded and the `M1` exclusion will be ignored.

I contacted GitHub support to ask about this.

**Comment by muratg** [comment]
Isn't ignoring `Backlog` enough for now?  We can add `Discussion`/`Discussions` milestones to the exclude list later.

**Comment by Eilon** [comment]
Turns out there's a way to do this: need to change URLs to go to `/search` (which allows fancier queries) instead of `/issues`, which is more restricted.

**Comment by muratg** [comment]
Cool. Though until you start using the search API, if you have another check-in (for the additional repos maybe), can you exclude `Backlog` only for now? It would very much reduce the error in the queries. (644 vs 900 in kcore)

**Comment by Eilon** [comment]
Fix is a few characters, will push in just a bit :smile:

**Comment by muratg** [comment]
:+1:

**Comment by Eilon** [comment]
Site is live. The numbers still seem to off by a tiny bit. Don't care :smile:
