### ISSUE TITLE
Change bug/PR queries to be sorted by 'Recently updated'

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#31]
Need to add `&s=updated` to the query string.

**Comment by muratg** [comment]
Did you get a chance to deploy this yet?

**Comment by Eilon** [comment]
Yeah it's been live since I closed the bug...

**Comment by muratg** [comment]
:+1: For some reason I thought this would update the ordering on the report page.

**Comment by Eilon** [comment]
Oh, no, that's kind of random :smile: Log a bug on it!
