### ISSUE TITLE
Store org along with repo sets to allow non-aspnet orgs to be listed

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#35]

**Comment by Eilon** [comment]
@MeniZalzman FYI

**Comment by muratg** [comment]
:+1:

**Comment by muratg** [comment]
One small nit: Octokit seems to use "owner" instead of "org".

**Comment by Eilon** [comment]
Ah, good point. I think in GitHub either an "org" or a "user" can each be an "owner." So "owner" is the more generic term. E.g. in this repo "Eilon" is not an "org," but rather a "user" who is an "owner."

I shall rename!

**Comment by Eilon** [comment]
Updated naming in https://github.com/Eilon/ProjectKIssueList/commit/c0eb2371e4443485f3ce02731ac48e074a5bb8bd.
