### ISSUE TITLE
Have a super-grid that shows counts/queries for every open milestone

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#38]
Have grid that shows for each milestone for each repo how many open bugs
- Use SemVer to sort all milestones (plus "no milestone")
- Ignore Discussion(s), Backlog milestones
- Each number links to a GitHub query

**Comment by Eilon** [comment]
![milestones](https://cloud.githubusercontent.com/assets/202643/10739137/02e5d6e2-7bd8-11e5-953b-f27ca56deda5.png)

**Comment by Eilon** [comment]
@muratg @divega you can now see a super grid with how many issues are in each milestone.

**Comment by muratg** [comment]
Thanks this is really useful!

**Comment by Eilon** [comment]
@yishaigalatzer @MeniZalzman @joshfree @Petermarcu you guys might also find this feature useful, especially to find random bugs sitting in ancient milestones.
