### ISSUE TITLE
Have the ability to pick repos

### ISSUE THREAD

**Issue by yishaigalatzer** [Eilon/Hubbup#39]
Either have a way to pick repos that the user has access to (org/repos selection with checkboxes and persistance)

Or use the link mechanism the Huboard supports (label links)

**Comment by Eilon** [comment]
Still no UI for it, but I'm most of the way to having a pull request model to update the list of repos.

**Comment by Eilon** [comment]
Closing because this is done. Just send PRs to https://github.com/Eilon/Hubbup-data to add/edit/remove repo sets.
