### ISSUE TITLE
Enable persistent logging

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#42]
Maybe use AppInsights? Need to track any errors that happen in the app.

**Comment by muratg** [comment]
Why log Serilog and an Azure sink?

**Comment by Eilon** [comment]
Will have to figure one out...

**Comment by Eilon** [comment]
Thoughts on stuff to track:

Date ranges: Last 7 days, last 4 weeks, ever.

Track these data points:
- page
- user
- user + page combo
