### ISSUE TITLE
Links to queries on RHS are missing the related labels

### ISSUE THREAD

**Issue by DamianEdwards** [Eilon/Hubbup#44]
https://projectkissuelist.azurewebsites.net/k-perf

Click one of the links under the "Issues" heading on the right-hand side and note that the expected filter to only show issues with the "perf" label hasn't been applied. Need to add "label:perf" to the query.

**Comment by Eilon** [comment]
Duh, forgot about that. Will fix soon.

**Comment by Eilon** [comment]
It's live.
