### ISSUE TITLE
Make repo list in each repo be a grid summarizing all the issues/PRs

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#52]
The items within the grid should be links to the issues/PRs of that repo, filtered as appropriate.

**Comment by Eilon** [comment]
This is what it looks like now:

![super-grid](https://cloud.githubusercontent.com/assets/202643/10409767/a36be8d0-6ee1-11e5-8756-da1742f3c393.png)

**Comment by muratg** [comment]
Nice. Looking forward to having the numbers/cells as links as well :)

What are the color codes?

**Comment by Eilon** [comment]
@muratg @divega @yishaigalatzer @MeniZalzman @danroth27 - ya'll might find this grid helpful. (Click the blue "Included repos" button to show the grid.)

Of course, if it's _not_ useful, please let me know :smile:

**Comment by Eilon** [comment]
Ah, color codes: red = stale PR, green = non-zero number. Nothing fancy :smile: 

Links coming soon.

**Comment by Eilon** [comment]
And soon == not tonight :smile:

**Comment by Eilon** [comment]
Now with links! And slightly updated colors.

![updated-super-grid](https://cloud.githubusercontent.com/assets/202643/10418919/c07e67ae-701c-11e5-8cc4-10ba1f1538d5.png)

**Comment by Eilon** [comment]
This is now live. Please note that _some_ queries don't exclude all the excluded milestones (e.g. Backlog, Discussion, Discussions) so you'll sometimes see a few extra issues, but hopefully it's not too much noise. The underlying issue is a query limit in GitHub's query processing, so not much that can be done here.
