### ISSUE TITLE
Incorrect queries in the new "per milestone" repo list

### ISSUE THREAD

**Issue by muratg** [Eilon/Hubbup#56]
**Issues**:
- `No milestone` column creates queries like `https://github.com/aspnet/dnvm/issues?q=is:open%20is:issue%20milestone:` (`/s/milestone:/no:milestone`)
- If a milestone has spaces in in, the query `https://github.com/aspnet/DataProtection/issues?q=is:open%20is:issue%20milestone:1.0.0%20backlog` doesn't show any bugs. (Add quotes around the milestone for all the queries)

**Comment by Eilon** [comment]
@muratg fixed and live!

**Comment by muratg** [comment]
Thanks, works great!
