### ISSUE TITLE
File name too long while cloning

### ISSUE THREAD

**Issue by sajayantony** [Eilon/Hubbup#68]
On windows - 

```
$ git clone https://github.com/Eilon/ProjectKIssueList Hubbup2
Cloning into 'Hubbup2'...
remote: Counting objects: 4464, done.
remote: Total 4464 (delta 0), reused 0 (delta 0), pack-reused 4464 eceiving objects:  99% (
Receiving objects: 100% (4464/4464), 4.44 MiB | 2.35 MiB/s, done.
Resolving deltas: 100% (1532/1532), done.
Checking connectivity... done.
fatal: cannot create directory at 'src/Hubbup.Web/node_modules/gulp-cssmin/node_modules/gul
ge-license/node_modules/spdx-correct/node_modules/spdx-license-ids': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by Eilon** [comment]
Clone it to something like `c:\GitHub` - that's the easiest solution :smile:

**Comment by analogrelay** [comment]
Why are the `node_modules` checked in anyway?

**Comment by analogrelay** [comment]
Btw, I cloned into `C:\d\ProjectKIssueList` and it was still too long.. Same when I tried `C:\d\k` and `C:\k`.

Going to try cloning on my Mac and shortening the folders...

**Comment by Eilon** [comment]
There's a PR out to clean all the node_modules stuff. I need to look into merging that.

**Comment by analogrelay** [comment]
I'll send a PR to update to RTM and include that in it when I finish my testing :)

**Comment by Eilon** [comment]
The PR that's open now is to update to RC2. So you could probably base a new PR off of that fork.

**Comment by analogrelay** [comment]
That's what I'm doing :)

**Comment by Eilon** [comment]
Niiiiiiiiice!

**Comment by Eilon** [comment]
A couple people named @JunTaoLuo and @anurse made Hubbup's code way more awesome than it ever was, so `node_modules` is gone, and it should clone just fine now.
