### ISSUE TITLE
Add a new repo set "kcoreext"...

### ISSUE THREAD

**Issue by muratg** [Eilon/Hubbup#70]
... that includes repos that my team members are (or may be in the future) working on:
- dotnet/cli
- dotnet/corefx
- omnisharp/omnisharp-roslyn
- aspnet/Common
- aspnet/DependencyInjection
- aspnet/Diagnostics
- aspnet/MusicStore
- aspnet/Testing
- aspnet/Configuration
- aspnet/Options

**Comment by Eilon** [comment]
Done

**Comment by muratg** [comment]
Thanks!  Any chance you could bring it closer to kcore in the UI? :grin:

**Comment by Eilon** [comment]
$$$

**Comment by muratg** [comment]
Lunch on me tomorrow :100:

**Comment by Eilon** [comment]
John Howie.

**Comment by muratg** [comment]
Sounds good, I always wanted to go!

**Comment by Eilon** [comment]
I actually have a lunch mtg tomorrow :smile:

**Comment by muratg** [comment]
Bummer :)
