### ISSUE TITLE
Show multiple repo groups in a single page...

### ISSUE THREAD

**Issue by muratg** [Eilon/Hubbup#73]
- Merge per person issues for all the groups and show a single issue list for each person
- Show multiple tables for "Included repos" view (one per repo group)

I guess to do this, you'll need to list not names of the groups on top, but the names of managers. And each manager can own a few repo groups.

**Comment by muratg** [comment]
Outcome of this would be the following for me:
- I  would see two "Included repos" buttons... one for kcore group and one for kcoreext
- Each person will have all the bugs/PRs assigned to them in the combined repo list of kcore and kcorext

**Comment by Eilon** [comment]
Not going to do this, but will do https://github.com/Eilon/ProjectKIssueList/issues/75 instead.
