### ISSUE TITLE
Group assignee-only repos in a separate super grid

### ISSUE THREAD

**Issue by Eilon** [Eilon/Hubbup#75]
Right now they're interleaved in the main super-grids, but they ought to be separate.

**Comment by muratg** [comment]
Any updates on this? :santa:

**Comment by Eilon** [comment]
@muratg the change is live, but I won't push the code to GitHub until I clean it up 😄

**Comment by muratg** [comment]
THANKS! Looks great :smile:

**Comment by Eilon** [comment]
Already did this issue, forgot to close it.
