### ISSUE TITLE
Support multiple-assignees

### ISSUE THREAD

**Issue by muratg** [Eilon/Hubbup#88]
Currently if a bug is assigned to two people, it's only shown in the first assignee's list.

**Comment by Eilon** [comment]
Waiting on https://github.com/octokit/octokit.net/issues/1334.

**Comment by Eilon** [comment]
This is now done:

> ![image](https://user-images.githubusercontent.com/202643/34322798-a4b9aaa8-e7e6-11e7-89b7-47a8760c3bd7.png)
